#include "gpio.h"

void gpio_init()
{
    //RCC->APB2PCENR |= RCC_IOPAEN;
    //GPIOA->CFGLR |= GPIO_CFGLR_MODE0;
    //GPIOA->CFGLR &= ~GPIO_CFGLR_CNF0;

    //GPIOA->CFGLR |= GPIO_CFGLR_MODE1;
    //GPIOA->CFGLR &= ~GPIO_CFGLR_CNF1;
    
    // p/p D3 up
    RCC->APB2PCENR |= RCC_IOPDEN;
    GPIOD->CFGLR |= GPIO_CFGLR_MODE3;
    GPIOD->CFGLR &= ~GPIO_CFGLR_CNF3;
    GPIOD->OUTDR |= GPIO_OUTDR_ODR3;
    
    // p/p D4 down
    GPIOD->CFGLR |= GPIO_CFGLR_MODE4;
    GPIOD->CFGLR &= ~GPIO_CFGLR_CNF4;
    GPIOD->OUTDR &= ~GPIO_OUTDR_ODR4;
    
    // p/p D2 down
    GPIOD->CFGLR |= GPIO_CFGLR_MODE2;
    GPIOD->CFGLR &= ~GPIO_CFGLR_CNF2;
    GPIOD->OUTDR &= ~GPIO_OUTDR_ODR2;
    
    // p/p C7 down
    RCC->APB2PCENR |= RCC_IOPCEN;
    GPIOC->CFGLR |= GPIO_CFGLR_MODE7;
    GPIOC->CFGLR &= ~GPIO_CFGLR_CNF7;
    GPIOC->OUTDR &= ~GPIO_OUTDR_ODR7;
}
