#include "gpio.h"

void gpio_init()
{
    RCC->APB2PCENR |= RCC_IOPAEN;
    GPIOA->CFGLR |= GPIO_CFGLR_MODE0;
    GPIOA->CFGLR &= ~GPIO_CFGLR_CNF0;

    GPIOA->CFGLR |= GPIO_CFGLR_MODE1;
    GPIOA->CFGLR &= ~GPIO_CFGLR_CNF1;
    
    RCC->APB2PCENR |= RCC_IOPCEN;
    GPIOC->CFGLR |= GPIO_CFGLR_MODE1;
    GPIOC->CFGLR &= ~GPIO_CFGLR_CNF1;
}
