#! /bin/sh
function_to_fork1() {
    sleep 0.5
    echo "+---------------------------------------------------+"
    echo "|                  ***   GDB  ***                   |"
    echo "+---------------------------------------------------+"
    gdb-multiarch
    killall -9 openocd
}

# ... execution continues in parent process ..

function_to_fork2() {
    echo "+---------------------------------------------------+"
    echo "|              ***  OPENOCD   ***                   |"
    echo "+---------------------------------------------------+"
    "/opt/openocd/bin/openocd" "-c" "gdb_port 3333" \
    "-s" "/opt/openocd/share/openocd/scripts" "-f" "./lib/wch-riscv.cfg" 
    echo "+---------------------------------------------------+"
    echo "|         ***  OPENOCD  KILLED ***                  |"
    echo "+---------------------------------------------------+"
    echo "killed function to fork"

}

function_to_fork2 &
pidApp1=$!
echo $pidApp1
function_to_fork1 
kill -9 $pidApp1
#sleep 1
killall -9 openocd
#sleep 0.1
echo "+---------------------------------------------------+"
echo "|         ***  OPENOCD  KILLED ***                  |"
echo "+---------------------------------------------------+"


# not always close openocd
