#include "gpio.h"

void gpio_init()
{
    RCC->APB2PCENR |= RCC_IOPAEN;
    // floating input mode
    GPIOA->CFGLR |= GPIO_CFGLR_MODE0;
    GPIOA->CFGLR |= GPIO_CFGLR_CNF0_0;
    GPIOA->CFGLR &= ~GPIO_CFGLR_CNF0_1;

    RCC->APB2PCENR |= RCC_IOPAEN;
    GPIOA->CFGHR |= GPIO_CFGHR_MODE15;
    GPIOA->CFGHR &= ~GPIO_CFGHR_CNF15;
    GPIOA->CFGHR |= GPIO_CFGHR_MODE9 | GPIO_CFGHR_MODE10 | GPIO_CFGHR_MODE11 |
                    GPIO_CFGHR_MODE12;
    GPIOA->CFGHR &= ~(GPIO_CFGHR_CNF9 | GPIO_CFGHR_CNF10 | GPIO_CFGHR_CNF11 |
                      GPIO_CFGHR_CNF12);
    //GPIOA->CFGLR |= GPIO_CFGLR_MODE4 | GPIO_CFGLR_MODE5;
    //GPIOA->CFGLR &= ~(GPIO_CFGLR_CNF4 | GPIO_CFGLR_CNF5);
    RCC->APB2PCENR |= RCC_IOPBEN;
    GPIOB->CFGLR |= GPIO_CFGLR_MODE4;
    GPIOB->CFGLR &= ~GPIO_CFGLR_CNF4;
    GPIOB->CFGHR |= GPIO_CFGHR_MODE12 | GPIO_CFGHR_MODE13 | GPIO_CFGHR_MODE14 |
                    GPIO_CFGHR_MODE15;
    GPIOB->CFGHR &= ~(GPIO_CFGHR_CNF12 | GPIO_CFGHR_CNF13 |
                      GPIO_CFGHR_CNF14 | GPIO_CFGHR_CNF15);
    RCC->APB2PCENR |= RCC_IOPDEN;
    GPIOD->CFGHR |= GPIO_CFGHR_MODE8 | GPIO_CFGHR_MODE9 | GPIO_CFGHR_MODE10 |
                    GPIO_CFGHR_MODE11 | GPIO_CFGHR_MODE12 | GPIO_CFGHR_MODE13 |
                    GPIO_CFGHR_MODE14 | GPIO_CFGHR_MODE15;
    GPIOD->CFGHR &=
        ~(GPIO_CFGHR_CNF8 | GPIO_CFGHR_CNF9 | GPIO_CFGHR_CNF10 |
          GPIO_CFGHR_CNF11 | GPIO_CFGHR_CNF12 | GPIO_CFGHR_CNF13 |
          GPIO_CFGHR_CNF14 | GPIO_CFGHR_CNF15);
}
